### ISSUE TITLE
compilation error on Ubuntu 16.04

### ISSUE THREAD

**Issue by trappedinspacetime** [bayi/qdmenu#1]
First of all congrats on your project. I am running Ubuntu 16.04 32 bit on an old low specs laptop. I created a custom session based on `Avant Window Navigator`,  I am trying  lightweight `Application Launchers`.  Yours `qdmenu`  looks good but  I get error while compiling it. 

      main.cpp:20:33: error: expected primary-expression before ‘>’ token
           qmlRegisterType<Applications>("Applications", 1, 0, "Applications");

I am not good at `c++`, how can I fix it?

Regards.
Kenn

**Comment by bayi** [comment]
Sorry i missed this issue, had a rough december ...

Can u please give me the following information whats currently included in ubuntu:
 - Gcc vversion ( gcc -v )
 - QT version

**Comment by trappedinspacetime** [comment]
@bayi I am sorry to hear that you had hard days.
`Qt version 5.5.1`
`gcc version 5.4.0`

**Comment by bayi** [comment]
The good nows is i fixed the compilation on Ubuntu, but the project depends on QtQuick 2.7 wichi think is only available in Qt>5.7. 
Im committing the fix now can u please test it if it runs ?

**Comment by bayi** [comment]
K my friend helped me to get this working, my fix above fixed the compile now i edited the versions of the qt modules so it runs also with qt 5.5 ( last commit ) 
You need the following modules just to be sure to run it:
 qtdeclarative5-qtlocation-plugin
 
And theese for compiling ( if you dont have it already ):
 qtdeclarative5-dev
 libqt5svg5-dev

**Comment by trappedinspacetime** [comment]
I just built and tried it. It built successfuly, when I launched, it complained about `qtlocation is not installed`. After I installed `qml-module-qtlocation`, gui launched and application icons appeared after processing icons. 
Thank you for your help :)

**Comment by bayi** [comment]
Your welcome, and again sorry for the delay.
