### ISSUE TITLE
Sluggish movement & needed configurations

### ISSUE THREAD

**Issue by EliaHKM** [bayi/qdmenu#2]
Hi 🙋🏻,
Qdmenu is good full-screen launcher however it's a bit sluggish when you move around.
it will good thing to add an option to configure it (bg-color, fg-color, opacity, blur and font) 

have a good day mate,

✌🏻

**Comment by bayi** [comment]
Thank you for the feedback.

Honestly im using it with i3 where it is always fullscreen covering my entire screen, never noticed how it moves around, thnx for the report ill look into it.

I already played with the idea to add some level of customization.

You could help me decide which route we should take:
 - Adding command line arguments only ( like --bg-color #ff0000 for red etc. )
 - Adding some sorf of (json maybne?) .config file in ~/.config

**Comment by EliaHKM** [comment]
Hi again 
I believe the second choice will be more flexible specially when you rice you DE/WM 
you can make the config file for every rice you have.

have a good day mate,
✌🏻

**Comment by bayi** [comment]
Please check out the latest version:

 - Configuration support ( its uses XDG by default its located at ~/.config/bayi/qdmenu.conf the file is created with defaults on first start )
 -  Major performance improvements, the parser and imageprovider is mostly rewritten
 - All apps are detected now (even the chrome/firefox etc installed pwa apps) fixed terminal support and fixed custom action support
 - Terminal (and NoDisplay) apps are by default hidden, the ctrl key toggles them
 -  Apps are displaying the localized names now but the search still searches for the following in order: name, localized name, generic name, localized generic name, keywords, comment
 -  Rewrote the mouse functions, the mouse hover change is gone, apps still can be selected by the mouse ( 2 clicks ) keyboard navigation / selection is more consistent now
  - Bumped QT versions ( somebody with Debian/Ubuntu please confirm that it still works on recent Arch it builds fine )
  - Fine tuned the animations a bit ( removed the x,y translation and only kept mostly the scale animations also sped them app ) 
  -  Fixed invisible apps bug ( and a lot other bugs )

Hope theese cover everything you wanted, and sorry that it took so long. If you need anything else ( more settings are planned and are coming soon ) let me know.
